version: "3"

services:
  web:
    build: ./docker/python/Dockerfile.prod
    env_file:
      - .env
    ports:
      - 5000:5000
    volumes:
        - .:/usr/src/app

  elasticsearch:
    container_name: elasticsearch
    hostname: elasticsearch
    image:  docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    environment:
      - http.host=0.0.0.0
      - bootstrap.memory_lock=true
    ports:
      - 9200:9200
    networks:
      - es-network

  kibana:
    container_name: kibana
    hostname: kibana
    image: docker.elastic.co/kibana/kibana:7.11.1
    environment:
      - elasticsearch.url=http://0.0.0.0:5000
      - server.name=kibana
    ports:
      - 5601:5601
    networks:
      - es-network
    depends_on:
      - elasticsearch
