# Generated by Django 3.2.6 on 2021-08-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='gear_case',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('variable', 'Variable'), ('semi-automatic', 'Semi-automatic')], default='manual', max_length=30),
        ),
    ]
